# Site settings
title: Annotify.app
email: annotify@annotify.app
description: Advanced data wrangling and applied scientometry for hybrid human-in-the-loop intelligenceware
twitter_username: annotifyapp
github_username:  annotifyapp

# Build settings
markdown: kramdown
