# Site settings
title: Annotify.app
email: annotify@annotify.app
description: Applied scientometry for hybrid intelligence
twitter_username: annotifyapp
github_username:  annotifyapp

# Build settings
markdown: kramdown
