# Site settings
title: farts LIVE!
email: annotify@annotify.app
description: Multi-geezer games for senile old farts who send fart memes to friends, using geezer dad joke superpowers to light fart memes--thus begins WW III of fart memes.
twitter_username: annotifyapp
github_username:  FARTSlive

# Build settings
markdown: kramdown
