# Site settings
title: Annotify.app
email: annotify@annotify.app
description: Making knowledgework FUNNER using computational linguistics analysis of neuromorphic response to build better workflows for hybrid human-machine intelligence.
twitter_username: annotifyapp
github_username:  annotifyapp

# Build settings
markdown: kramdown
