# Site settings
title: Annotify.app
email: annotify@annotify.app
description: An AWESOME checklist annotation workflow, but simpler perhaps ... for the not yet Git-enlightened.
twitter_username: MarkBruns
github_username:  annotifyapp

# Build settings
markdown: kramdown
