# Site settings
title: farts LIVE!
email: annotify@annotify.app
description: Multi-geezer game for senile bastards who send fart memes to friends, then using geezer superpowers to light fart memes, ushering in a WW III of fart memes.
twitter_username: annotifyapp
github_username:  FARTSlive

# Build settings
markdown: kramdown
