# Site settings
title: Annotify.app
email: annotify@annotify.app
description: If we can see further, it is because we always stand squarely on the shoulders of another duck.
twitter_username: annotifyapp
github_username:  annotifyapp

# Build settings
markdown: kramdown
