# Site settings
title: farts LIVE!
email: annotify@annotify.app
description: Fartlers bottling up the hippest gaseous vibe ... fartling today's vibeage to uncork it later and sniff it for the eternities!
twitter_username: annotifyapp
github_username:  FARTSlive

# Build settings
markdown: kramdown
