# Site settings
title: Annotify.app
email: annotify@annotify.app
description: AWESOME checklist annotation workflow ...simpler, for the not yet Git-enlightened
twitter_username: MarkBruns
github_username:  annotifyapp

# Build settings
markdown: kramdown
