# Site settings
title: Annotify.app
email: MarkBruns@MarkBruns.com
description: Research and exploring of best tools available for ToDoList / Annotated Bibliography / Research Journaling / RSS Newsreader
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
